FROM armdocker.rnd.ericsson.se/proj-eson-3pp/stubbed-enm

COPY ./test_data/pm_statistical /stubbed-enm/fls/files/pm_statistical
COPY ./test_data/pm_celltrace /stubbed-enm/fls/files/pm_celltrace
COPY ./test_data/bulk_export/ /bulk/export/